version: '3.7'

services:

	# Nginx
  nginx:
    container_name: nginx

    build: ./requirements/nginx/.
    image: nginx:42
    
    depends_on:
      - wordpress
    
    ports:
      - "443:443"

    volumes:
      - wordpress:/var/www/html
    
    networks:
      - inception

    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress

    build: ./requirements/wordpress/.
    image: wordpress:42

    depends_on:
      - mariadb

    volumes:
      -wordpress:/var/www/html

    env_file:
      - .env

    networks:
      - inception
    
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:42

    volumes:
      - mariadb:/var/lib/mysql

    env_file:
      - .env

    networks:
      - inception
    
    restart: always

networks:
  inception:
    name: inception
		
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/vboxuser/Desktop/42Inception/srcs/wordpress
      type: none
      o: bind
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/vboxuser/Desktop/42Inception/srcs/mariadb
      type: none
      o: bind


