
services:

  nginx:
    container_name: nginx

    build: ./requirements/nginx/.

    depends_on:
      - wordpress
    
    ports:
      - "443:443"

    volumes:
      - /home/nromito/data:/var/www/html
    
    networks:
      - inception

    env_file:
      - .env

    restart: always

  wordpress:
    container_name: wordpress

    build: ./requirements/wordpress/.

    ports:
      - "9000:9000"

    depends_on:
      mariadb:
        condition: service_healthy

    volumes:
      - /home/nromito/data:/var/www/html

    env_file:
      - .env

    networks:
      - inception
    
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

    volumes:
      - /home/nromito/data/mariadb:/var/lib/mysql

    env_file:
      - .env

    networks:
      - inception
    
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      device: /home/nromito/data/mariadb
      o: bind
  wordpress:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      device: /home/nromito/data
      o: bind



