version: '3.7'

services:

	# Nginx
  nginx:
    hostname: nginx

    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    
    restart: always

    depends_on:
      - wordpress
    
    ports:
      - 9000:9000

    volumes:
      - wordpress:/var/www/html
    
    networks:
      - web
		
