services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "9000:9000"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html:ro
    env_file:
      - .env
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/nromito/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/nromito/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge
